export const NEXT_ROUTES = {
  home: '/',
  games: '/games',
  category: '/category',
  provider: '/provider]',
  search: '/search',
  promotions: '/promotions',
  promotionDetail: '/promotions',
  vip: '/vip',
  legalTerms: '/legal/terms',
  legalPrivacy: '/legal/privacy',
  legalResponsibleGaming: '/legal/responsible-gaming',
  legalCookies: '/legal/cookies',
  notFound: '/404',
  error: '/500',
  maintenance: '/maintenance',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  profile: '/profile',
  settings: '/settings',
  affiliate: '/affiliate',
  vipClub: '/vip-club',
  blog: '/blog',
  forum: '/forum',
  sponsorships: '/sponsorships',
  liveSupport: '/live-support',
  language: '/language',
  casino: '/casino',
  sports: '/sports',
} as const

export const PUBLIC_ROUTES: string[] = [
  NEXT_ROUTES.home,
  NEXT_ROUTES.games,
  NEXT_ROUTES.category,
  NEXT_ROUTES.provider,
  NEXT_ROUTES.search,
  NEXT_ROUTES.promotions,
  NEXT_ROUTES.promotionDetail,
  NEXT_ROUTES.vip,
  NEXT_ROUTES.legalTerms,
  NEXT_ROUTES.legalPrivacy,
  NEXT_ROUTES.legalResponsibleGaming,
  NEXT_ROUTES.legalCookies,
  NEXT_ROUTES.notFound,
  NEXT_ROUTES.error,
  NEXT_ROUTES.maintenance,
  NEXT_ROUTES.login,
  NEXT_ROUTES.register,
  NEXT_ROUTES.forgotPassword,
  NEXT_ROUTES.resetPassword,
  NEXT_ROUTES.profile,
  NEXT_ROUTES.settings,
  NEXT_ROUTES.affiliate,
  NEXT_ROUTES.vipClub,
  NEXT_ROUTES.blog,
  NEXT_ROUTES.forum,
  NEXT_ROUTES.sponsorships,
  NEXT_ROUTES.liveSupport,
  NEXT_ROUTES.language,
]

// Update or remove NAVIGATION_HIDDEN_ROUTES as needed for your navigation logic
export const NAVIGATION_HIDDEN_ROUTES = [NEXT_ROUTES.notFound, NEXT_ROUTES.error, NEXT_ROUTES.maintenance]
