import { FC } from 'react'

import BottomBar from '@/composants/BottomBar/BottomBar'
import Footer from '@/composants/Footer/Footer'
import Header from '@/composants/Header/Header'
import SideMenu from '@/composants/Sidemenu/SideMenu'
import { Providers } from '@/providers'
import { Box, Toolbar } from '@mui/material'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: FC<
  Readonly<{
    children: React.ReactNode
  }>
> = ({ children }) => (
  <html lang="en">
    <head>
      <link rel="manifest" href="/manifest.json" />
      <meta name="theme-color" content="#0A2540" />
      <link rel="preload" as="image" href="/assets/images/casino.webp" />
      <link rel="preload" as="image" href="/assets/images/sport.webp" />
    </head>
    <body>
      <Providers>
        <Box sx={{ display: 'flex' }}>
          <SideMenu />
          <Box
            component="main"
            sx={{
              flexGrow: 1,
              bgcolor: 'background.default',
              width: 'calc(100vw - (100vw - 100%))',
              minHeight: { sx: '100vh' },
              overflowY: 'auto',
            }}
          >
            <Header />
            <Toolbar
              sx={{
                height: '76px',
              }}
            />
            {children}
            <Footer />
            <Toolbar
              sx={{
                height: '76px',
                display: { xs: 'block', md: 'none' },
              }}
            />
          </Box>
          <BottomBar />
        </Box>
      </Providers>
    </body>
  </html>
)

export default RootLayout
