import type { Metadata } from "next";
import { Providers } from "@/providers";
import { Box, Toolbar } from "@mui/material";
import Sidebar from "@/composants/Sidebar/Sidebar";
import Header from "@/composants/Header/Header";
import Footer from "@/composants/Footer/Footer";
import BottomBar from "@/composants/BottomBar/BottomBar";
import SideMenu from "@/composants/NewSidemenu/SideMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Box sx={{ display: "flex" }}>
            {/* <Sidebar /> */}
            <SideMenu />
            <Box
              component="main"
              sx={{
                flexGrow: 1,
                bgcolor: "background.default",
                width: "calc(100vw - (100vw - 100%))",
                minHeight: { sx: "100vh" },
                overflowY: "auto",
              }}>
              <Header />
              <Toolbar />
              {children}
              {/* <Toolbar /> */}
              {/* <Footer /> */}
            </Box>
            <BottomBar />
          </Box>
        </Providers>
      </body>
    </html>
  );
}
