import type { Metadata } from "next";
import { Providers } from "@/providers";
import { Box, Toolbar } from "@mui/material";
import Sidebar from "@/composants/Sidebar/Sidebar";
import Header from "@/composants/Header/Header";
import Footer from "@/composants/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Box sx={{ display: "flex" }}>
            <Header />
            <Sidebar />
            <Box
              component="main"
              sx={{ flexGrow: 1, bgcolor: "background.default", p: 3 }}>
              <Toolbar />
              {children}
              {/* <Footer /> */}
            </Box>
          </Box>
        </Providers>
      </body>
    </html>
  );
}
